[auth]
enabled = true

[edge_runtime]
enabled = true
policy = "per_worker"

[functions]
enabled = true

[functions.process-upload]
verify_jwt = false
import_map = "./functions/process-upload/import_map.json"
