steps:
  # 1. Compila a imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-west1-docker.pkg.dev/appcuidador-23628/cloud-run-source-deploy/foco-completo:$COMMIT_SHA', '.']
    id: 'Build'

  # 2. Envia a imagem para o Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-west1-docker.pkg.dev/appcuidador-23628/cloud-run-source-deploy/foco-completo:$COMMIT_SHA']
    id: 'Push'

  # 3. Realiza o deploy automático para o Cloud Run (foco-completo)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'services'
      - 'update'
      - 'foco-completo'
      - '--platform=managed'
      - '--image=us-west1-docker.pkg.dev/appcuidador-23628/cloud-run-source-deploy/foco-completo:$COMMIT_SHA'
      - '--region=us-west1'
      - '--quiet'
    id: 'Deploy'

images:
  - 'us-west1-docker.pkg.dev/appcuidador-23628/cloud-run-source-deploy/foco-completo:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
