-- ============================================================
-- Migration 005: Seed Data
-- Foco em Dados
-- ============================================================

-- ################################################################
-- 5.1. Plans (preços em centavos)
-- ################################################################
INSERT INTO public.plans (name, tier, description, price_monthly, price_yearly, limits_dashboards, limits_rows, limits_marketplaces, limits_chatbots, limits_api_calls, limits_storage_mb, features_json, sort_order) VALUES
  ('Gratuito',   'free',       'Para testar a plataforma sem compromisso.',                                  0,       0,      3,  2000,    1,   1,   0,    50,   '["templates_basicos", "upload_csv", "chatbot_basico", "comunidade_publica"]'::jsonb,                                                                                                           1),
  ('Starter',    'starter',    'Para pequenos lojistas que querem crescer.',                                  9700,   97000,  10, 50000,    3,   3,   1000,   500,  '["templates_premium", "alertas_automaticos", "exportacao_pdf", "relatorios_agendados", "comunidade_privada"]'::jsonb,                                                                            2),
  ('Pro',        'pro',        'Para negócios em expansão com equipe enxuta.',                                29700,  297000, 999999, 500000,  10, 999999, 10000,  2000, '["api_publica", "white_label", "forecast_basico", "benchmark_anonimo", "integracoes_ilimitadas", "suporte_tickets_48h"]'::jsonb,                                                                3),
  ('Business',   'business',   'Para equipes que precisam de análises avançadas.',                            59700,  597000, 999999, 999999, 999999, 999999, 100000, 10000, '["multiplos_usuarios", "forecast_avancado", "benchmark_segmentado", "suporte_tickets_24h", "onboarding_automatizado"]'::jsonb,                                                                   4),
  ('Enterprise', 'enterprise', 'Para grandes operações com demandas personalizadas.',                         99700,  997000, 999999, 999999, 999999, 999999, 999999, 100000,'["usuarios_ilimitados", "data_lake_dedicado", "ia_customizada", "sla_99_9", "suporte_prioritario", "dedicated_ip"]'::jsonb,                                                                      5);

-- ################################################################
-- 5.2. Addons (funcionalidades avulsas)
-- ################################################################
INSERT INTO public.addons (slug, name, description, price_monthly, price_yearly, category, features, sort_order) VALUES
  ('relatorios_agendados',  'Relatórios Agendados',  'Exportação automática de relatórios por e-mail em PDF/Excel.',                1900,  19000, 'export',      '["frequencia_diaria", "formato_pdf", "formato_excel", "multiplos_destinatarios"]'::jsonb,       1),
  ('integracao_whatsapp',   'Integração WhatsApp',   'Conecte seu chatbot ao WhatsApp oficial com Business API.',                   4900,  49000, 'integration', '["whatsapp_business_api", "template_messages", "analytics"]'::jsonb,                       2),
  ('exportacao_avancada',   'Exportação Avançada',   'Exporte dados em CSV, JSON e SQL com schedule automático.',                   2900,  29000, 'export',      '["formato_csv", "formato_json", "formato_sql", "schedule_personalizado"]'::jsonb,               3),
  ('api_publica',           'API Pública',            'Acesso programático a todos os seus dashboards e dados via REST API.',        7900,  79000, 'api',         '["rest_api", "api_keys", "webhooks", "rate_limit_5000"]'::jsonb,                                4),
  ('white_label',           'White Label',            'Remova a marca Foco em Dados e use seu próprio domínio e identidade visual.', 9900,  99000, 'customization','["dominio_prorpio", "logo_personalizada", "css_customizado", "remover_marca"]'::jsonb,         5),
  ('insights_ia',           'Insights por IA',        'Análises preditivas e recomendações automáticas com machine learning.',       14900, 149000,'ai',          '["previsao_demanda", "analise_sentimento", "recomendacoes", "alertas_inteligentes"]'::jsonb,   6),
  ('suporte_prioritario',   'Suporte Prioritário',    'Atendimento em até 2 horas úteis via chat e ticket prioritário.',            3900,  39000, 'automation',  '["chat_prioritario", "sla_2h", "gerente_dedicado"]'::jsonb,                                   7);

-- ################################################################
-- 5.3. Templates (marketplace de dashboards e fluxos)
-- ################################################################
INSERT INTO public.templates (name, description, category, subcategory, config_json, price, is_free, download_count, rating) VALUES
  ('Dashboard de Vendas - Moda',               'Acompanhe receita, ticket médio e produtos mais vendidos no segmento de moda.',                                                                               'vendas',     'moda',         '{"charts": [{"type": "line", "metric": "revenue"}, {"type": "bar", "metric": "top_products"}, {"type": "kpi", "metric": "avg_ticket"}]}'::jsonb,                                                                                                   0, true,  234, 4.7),
  ('Dashboard de Estoque',                     'Controle de estoque com alertas de reposição e previsão de demanda.',                                                                                         'estoque',    'geral',        '{"charts": [{"type": "bar", "metric": "stock_level"}, {"type": "line", "metric": "turnover"}, {"type": "kpi", "metric": "low_stock_count"}]}'::jsonb,                                                                                             0, true,  189, 4.5),
  ('Dashboard de Marketing - Meta Ads',        'Acompanhe ROAS, CTR, CPC e custo por conversão das suas campanhas.',                                                                                          'marketing',  'geral',        '{"charts": [{"type": "line", "metric": "roas"}, {"type": "bar", "metric": "ctr"}, {"type": "kpi", "metric": "cost_per_conversion"}]}'::jsonb,                                                                                                  19700, false, 87,  4.8),
  ('Chatbot - Atendimento Moda',               'Fluxo completo de atendimento para loja de moda com perguntas frequentes.',                                                                                   'chatbot',    'moda',         '{"flows": [{"trigger": "trocar", "response": "Claro! Qual o número do pedido?"}, {"trigger": "tamanho", "response": "Temos do P ao GG. Qual você precisa?"}, {"trigger": "prazo", "response": "O prazo médio é de 7 dias úteis."}]}'::jsonb,     0, true,  312, 4.6),
  ('Previsão de Demanda - Alimentação',        'Preveja demanda por produto com base em dados históricos e sazonalidade.',                                                                                    'vendas',     'alimentacao',  '{"model": "time_series", "forecast_days": 30, "charts": [{"type": "line", "metric": "forecast"}, {"type": "area", "metric": "demand"}]}'::jsonb,                                             29700, false, 45,  4.9),
  ('Dashboard Financeiro',                     'Acompanhe DRE, fluxo de caixa e margem por produto.',                                                                                                          'financeiro', 'geral',        '{"charts": [{"type": "line", "metric": "cash_flow"}, {"type": "pie", "metric": "expenses_by_category"}, {"type": "kpi", "metric": "gross_margin"}]}'::jsonb,                                                                                      0, true,  156, 4.3),
  ('Dashboard de Vendas - Geral',              'Template genérico de vendas para qualquer segmento do varejo.',                                                                                               'vendas',     'geral',        '{"charts": [{"type": "line", "metric": "revenue"}, {"type": "pie", "metric": "sales_by_category"}, {"type": "bar", "metric": "daily_sales"}]}'::jsonb,                                                                                            0, true,  567, 4.4);

-- ################################################################
-- 5.4. FAQ Documents (para chatbot RAG)
-- ################################################################
INSERT INTO public.documents (title, content, category, tags) VALUES
  ('Como conectar minha loja Shopify?',             'Vá em Configurações > Integrações > Shopify. Clique em "Conectar" e autorize o acesso da Foco em Dados aos seus dados. Você será redirecionado para a página de autenticação da Shopify.',                                                                                                                                                                    'Integrações', '["shopify", "integracao", "conexao"]'::jsonb),
  ('Como fazer upload de planilha?',                 'Acesse a página Upload e arraste seu arquivo CSV ou Excel na área pontilhada. Formatos aceitos: .csv, .xlsx, .xls. Tamanho máximo: 10MB. Colunas mínimas necessárias: produto, quantidade, valor.',                                                                                                                                                             'Upload',      '["upload", "planilha", "csv", "excel"]'::jsonb),
  ('Como criar alertas de estoque?',                 'No dashboard de Estoque, clique em "Configurar Alertas" no canto superior direito. Defina o limite mínimo por produto ou categoria. Você receberá uma notificação quando o estoque atingir o limite.',                                                                                                                                                        'Dashboards',  '["alerta", "estoque", "notificacao"]'::jsonb),
  ('Como gerar previsão de vendas?',                 'No dashboard, clique no botão "Gerar Previsão" no painel de métricas. A IA analisa seus dados históricos dos últimos 12 meses e gera uma projeção para os próximos 30 dias.',                                                                                                                                                                                  'Dashboards',  '["previsao", "forecast", "ia", "vendas"]'::jsonb),
  ('Como fazer upgrade de plano?',                   'Clique no seu plano atual no canto superior direito do header e selecione "Fazer Upgrade". Escolha o novo plano e finalize o pagamento. As novas funcionalidades ficam disponíveis imediatamente.',                                                                                                                                                            'Planos',      '["upgrade", "plano", "assinatura", "pagamento"]'::jsonb),
  ('Como configurar chatbot no WhatsApp?',           'Vá em Chatbots > Novo Chatbot. Selecione "WhatsApp" como plataforma. Configure o fluxo de conversa no editor visual. Para conectar ao WhatsApp oficial, você precisa de uma conta Business Meta.',                                                                                                                                                            'Chatbots',    '["chatbot", "whatsapp", "bot", "automacao"]'::jsonb),
  ('Quais integrações estão disponíveis?',           'Shopify, WooCommerce, Mercado Livre, Shopee, Bling, Omie, Tiny, Google Sheets, Meta Ads e Google Ads. Acesse Configurações > Integrações para conectar.',                                                                                                                                                                                                      'Integrações', '["integracao", "shopify", "woocommerce", "mercado_livre", "shopee", "bling"]'::jsonb),
  ('Como convidar membros da equipe?',             'O plano Business permite até 5 usuários. Vá em Configurações > Equipe e clique em "Convidar". Envie o link de convite por email. O convidado precisa criar uma conta para acessar.',                                                                                                                                                                           'Planos',      '["equipe", "usuarios", "convite", "business"]'::jsonb),
  ('Como funciona o programa de afiliados?',         'Compartilhe seu link único de afiliado. Quando alguém assinar um plano pago usando seu link, você ganha 20% de comissão sobre o valor da primeira mensalidade. Saques a partir de R$ 50 via Pix.',                                                                                                                                                           'Afiliados',   '["afiliado", "comissao", "referral", "pix", "saque"]'::jsonb),
  ('Como exportar relatórios?',                      'No dashboard, clique no ícone de exportação no canto superior direito. Escolha entre PDF, PNG ou Excel. Relatórios agendados podem ser configurados em Configurações > Relatórios Agendados.',                                                                                                                                                              'Dashboards',  '["exportar", "relatorio", "pdf", "excel", "agendado"]'::jsonb),
  ('O que é o modo trial?',                          'Ao criar sua conta, você ganha 7 dias de teste gratuito com acesso a todos os recursos do plano Pro. Seu cartão não é cobrado durante o período. Ao final, você pode escolher um plano ou continuar no plano Gratuito.',                                                                                                                                        'Planos',      '["trial", "teste", "gratuito", "7_dias"]'::jsonb),
  ('Como funciona o limite de linhas?',              'Cada plano tem um limite mensal de linhas processadas. O plano Gratuito permite 2.000 linhas/mês. Ao atingir o limite, você recebe uma notificação e pode fazer upgrade para continuar usando. O limite é resetado no primeiro dia de cada mês.',                                                                                                                 'Planos',      '["limite", "linhas", "consumo", "upgrade"]'::jsonb);
